services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-contract_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - contract-api-network

  app:
    build: .
    command: poetry run start
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - contract-api-network

networks:
  contract-api-network:

volumes:
  postgres_data: