from .union_routes import union_bp
from .sei_routes import sei_bp
from .address_routes import address_bp
from .organization_client_routes import organization_client_bp
from .contract_routes import contract_bp
from .attachment_routes import attachment_bp
from .general_information_routes import general_information_bp
from .item_routes import item_bp
from .role_routes import role_bp
from .reassignment_routes import reassignment_bp
from .additional_routes import additional_bp
from .contact_routes import contact_bp